@host = localhost:8080

// Access a Secured API Endpoint
GET http://{{host}}/api/secured/ping HTTP/1.1
content-type: application/json
authorization: $2a$14$wn7jIpXVk/W5d3ks00gAZuM4adEI2YSZqcmNtzwh9mf9ASxBbQ38.

###